version: '3.4'

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: compass
      POSTGRES_USER: compass
      POSTGRES_PASSWORD: compass
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
  web:
    build:
      context: ./
      network: host
    command: "gunicorn TourCompass.wsgi:application --bind 0.0.0.0:8000 --worker-tmp-dir /tmp --workers 5 --worker-class=gthread --timeout=120 --graceful-timeout=15"
    ports:
      - "8000:8000"
    env_file:
      - .env.docker # hidden 4 demonstration
    depends_on:
      - db
    restart: always