# Generated by Django 4.2.7 on 2024-02-24 14:11

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MonthOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=1028, null=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5),
                                                                      django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=2056, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
