# Generated by Django 4.2.7 on 2024-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directions', models.JSONField(blank=True, null=True)),
                ('season', models.CharField(blank=True, choices=[('Лето', 'Лето'), ('Зима', 'Зима'),
                                                                 ('Круглый Год', 'Круглый Год')], null=True)),
                ('services', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.JSONField(blank=True, null=True)),
                ('main_info', models.JSONField(blank=True, null=True)),
                ('payment_info', models.JSONField(blank=True, null=True)),
                ('types_info', models.ManyToManyField(blank=True, to='objects.typeinfo')),
            ],
        ),
    ]
